export const categoryOptions = [
  { id: 1, label: "Salary/Wages", icon: "Briefcase" },
  { id: 2, label: "Freelance/Consulting", icon: "Laptop" },
  { id: 3, label: "Business Income", icon: "CreditCard" },
  { id: 4, label: "Investment Income", icon: "CandlestickChart" },
  { id: 5, label: "Rental Income", icon: "Home" },
  { id: 6, label: "Side Hustle Income", icon: "Wallet2" },
  { id: 7, label: "Gifts/Inheritance", icon: "Gift" },
  { id: 8, label: "Alimony/Child Support", icon: "Baby" },
  { id: 9, label: "Royalties", icon: "CircleDollarSign" },
  { id: 10, label: "Social Security/Pension", icon: "CircleDollarSign" },
  { id: 11, label: "Rent/Mortgage", icon: "Home" },
  { id: 12, label: "Utilities", icon: "Cable" },
  { id: 13, label: "Food/Groceries", icon: "Drumstick" },
  { id: 14, label: "Transportation", icon: "TramFront" },
  { id: 15, label: "Healthcare/Medical", icon: "HeartPulse" },
  { id: 16, label: "Debt Payments", icon: "Receipt" },
  { id: 17, label: "Entertainment/Leisure", icon: "Clapperboard" },
  { id: 18, label: "Education", icon: "BookText" },
  { id: 19, label: "Personal Care", icon: "Dumbbell" },
  { id: 20, label: "Savings/Investments", icon: "WalletCards" },
];
